//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUBiblioteca
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Libro
    {
        public int id_lib { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El titulo del libro es requerido"), MaxLength(70)]
        [Display(Name = "Titulo del Libro")]
        public string titulo_lib { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Los autores del libro son requeridos"), MaxLength(55)]
        [Display(Name = "Autor/es del Libro")]
        public string autores_lib { get; set; }
        [Display(Name ="ISBN")]
        [Required(ErrorMessage = "ISBN es Requerido"), MaxLength(13)]
        public string ISBN_lib { get; set; }
        [Display(Name = "Fecha de Publicación")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> fch_public_lib { get; set; }
        [Display(Name = "Número de Ejemplares")]
        public Nullable<int> num_ejem_lib { get; set; }
        [Display(Name = "Categoría")]
        public Nullable<int> id_categoria { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
