//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUBiblioteca
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Video
    {
        public int id_vdo { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El titulo del Video es requerido"), MaxLength(50)]
        [Display(Name = "Titulo del Video")]
        public string titulo_vdo { get; set; }
        [Display(Name = "Fecha de Publicación")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> fch_public_vdo { get; set; }
        [Display(Name = "Duración")]
        public Nullable<double> duracion_vdo { get; set; }
        [Display(Name ="Categoría")]
        public Nullable<int> id_categoria { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
